# Use the official nginx image as the base
FROM nginx:latest

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy a custom nginx configuration file if you want
# COPY nginx.conf /etc/nginx/conf.d/

# Copy the frontend static files to the nginx directory
COPY ./frontend /usr/share/nginx/html

# Expose port 80 to the host
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]

